services:
  - type: web
    name: node-clase
    env: node
    region: ohio
    buildCommand: npm install
    startCommand: node app/server.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_CONNECTION_LIMIT
        value: "10"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
    healthCheckPath: /
    autoDeploy: true 